version: '3'

services:
  postgres-db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Australia/Melbourne"
    ports:
      - '5432:5432'
